[package]
name = "rust-codespaces"
version = "0.1.0"
authors = ["Your Name"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
	

[dependencies]
rocket = { git = "https://github.com/SergioBenitez/Rocket", rev = "4dcd928" }
